name: YouTube Music Scrobble Sync

on:
  schedule:
    - cron: '0 23 * * *'  # Daily at 23:00 UTC (adjust as needed)
  workflow_dispatch: # Allows manual triggering from GitHub UI

jobs:
  scrobble:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run YouTube Music Scrobbler
        env:
          LAST_FM_API: ${{ secrets.LAST_FM_API }}
          LAST_FM_API_SECRET: ${{ secrets.LAST_FM_API_SECRET }}
          YTMUSIC_COOKIE: ${{ secrets.YTMUSIC_COOKIE }}
          LASTFM_SESSION: ${{ secrets.LASTFM_SESSION }}
        run: |
          set -e
          python start_standalone.py > output.log 2>&1

      - name: Send success notification
        if: success()
        run: |
          curl -H "Content-Type: application/json" \
               -d "{\"content\": \"✅ YouTube Music Scrobble Sync **completed successfully!**\"}" \
               ${{ secrets.DISCORD_WEBHOOK_URL }}

      - name: Send failure notification
        if: failure()
        run: |
          echo "Workflow failed, sending Discord alert..."
          LOG_OUTPUT=$(tail -n 20 output.log | sed 's/"/\\"/g')
          curl -H "Content-Type: application/json" \
               -d "{\"content\": \"❌ YouTube Music Scrobble Sync **failed!**\n\n\`\`\`\n${LOG_OUTPUT}\n\`\`\`\"}" \
               ${{ secrets.DISCORD_WEBHOOK_URL }}