name: YouTube Music Scrobble Sync

on:
  schedule:
    - cron: '0 23 * * *'  # Daily at 23:00 UTC (adjust as needed)
  push:
    branches: [master] # Trigger on push to main branch
  workflow_dispatch: # Allows manual triggering from GitHub UI

jobs:
  scrobble:
    runs-on: ubuntu-latest
    environment: production # Binds to the 'production' environment for secrets and protection rules
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11' # Or your preferred Python version (e.g., '3.8', '3.9', '3.10')
          
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run YouTube Music Scrobbler
        env:
          LAST_FM_API: ${{ secrets.LAST_FM_API }}
          LAST_FM_API_SECRET: ${{ secrets.LAST_FM_API_SECRET }}
          YTMUSIC_COOKIE: ${{ secrets.YTMUSIC_COOKIE }}
        run: |
          echo "Starting YouTube Music Scrobbler..."
          python start_standalone.py
          echo "YouTube Music Scrobbler finished."
        
  notify:
    needs: scrobble
    runs-on: ubuntu-latest
    if: failure()
    steps:
      - name: Send Discord notification
        run: |
          curl -H "Content-Type: application/json" -d '{
            "content": "YouTube Music Scrobble Sync failed!"
          }' "$DISCORD_WEBHOOK_URL"
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}